# Generated by Django 5.0.6 on 2024-05-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_prefix",
                    models.CharField(
                        choices=[
                            ("FTA", "FTA"),
                            ("FBA", "FBA"),
                            ("FXA", "FXA"),
                            ("FGA", "FGA"),
                            ("FNA", "FNA"),
                            ("AIB", "AIB"),
                            ("AGA", "AGA"),
                        ],
                        max_length=3,
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("line", models.PositiveIntegerField(null=True)),
                ("place", models.PositiveIntegerField(null=True)),
                ("quantity", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["line", "place"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("order_number", models.CharField(max_length=20, unique=True)),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEL", "Delivered"),
                            ("INP", "In Progress"),
                            ("ONH", "On Hold"),
                            ("CAN", "Cancelled"),
                            ("COM", "Completed"),
                        ],
                        default="INP",
                        max_length=3,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="locator.item"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="locator.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                through="locator.OrderItem", to="locator.item"
            ),
        ),
    ]
