# Generated by Django 5.0.6 on 2024-05-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="model_prefix",
            field=models.CharField(
                choices=[
                    ("FTA", "FTA"),
                    ("FBA", "FBA"),
                    ("FXA", "FXA"),
                    ("FGA", "FGA"),
                    ("FNA", "FNA"),
                    ("AIB", "AIB"),
                    ("AGA", "AGA"),
                    ("II", "II"),
                    ("CCC", "CCC"),
                    ("CFA", "CFA"),
                    ("CGA", "CGA"),
                    ("CNA", "CNA"),
                    ("CPA", "CPA"),
                    ("CSB", "CSB"),
                    ("CTA", "CTA"),
                    ("CXA", "CXA"),
                    ("CXB", "CXB"),
                    ("F01", "F01"),
                    ("F02", "F02"),
                    ("F07", "F07"),
                    ("FGA", "FGA"),
                    ("FHY", "FHY"),
                    ("FIB", "FIB"),
                    ("FLA", "FLA"),
                    ("FNA", "FNA"),
                    ("FPA", "FPA"),
                    ("FTA", "FTA"),
                    ("FXA", "FXA"),
                    ("FXB", "FXB"),
                    ("FXT", "FXT"),
                    ("СXA", "СXA"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("number", "model_prefix")},
        ),
    ]
